Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "centos1" do |centos1|
    centos1.vm.hostname = "centos1"
    centos1.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "centos2" do |centos2|
    centos2.vm.hostname = "centos2"
    centos2.vm.network "private_network", ip: "192.168.56.11"
  end

  config.vm.define "centos3" do |centos3|
    centos3.vm.hostname = "centos3"
    centos3.vm.network "private_network", ip: "192.168.56.12"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
  end
end
